Added in code to process Wikidata, generate gold and negative links
verneek-interns/retrieval_augmented_linking pull request #10
Opened 2021-07-09 22:17 UTC by anthonywchen

Added code into `retrieval_augmented_generation` to process Wikidata, generate gold links, and generate negative links

2021-07-09 22:17 UTC, anthonywchen commented
Resolves issues #1 and #2

2021-07-12 16:20 UTC, anthonywchen commented
@samanz-verneek

2021-07-12 20:20 UTC, samanz-verneek reviewed
Code looks pretty good. Not urgent, but these are the kind of methods that would benefit from testing.

2021-07-13 15:32 UTC, anthonywchen commented on retrieval_augmented_linking/generate_data/extract_entity_relations.py
> +    if "\"enwiki\"" not in line and "\"type\":\"item\"" in line:
good point.

2021-07-13 15:32 UTC, anthonywchen commented on retrieval_augmented_linking/generate_data/extract_entity_relations.py
> +def main():
yeah that's a good idea. I'll leave this to until the end though. If you have a repo where you have an example of this that'd be good.

2021-07-13 15:33 UTC, anthonywchen commented on retrieval_augmented_linking/generate_data/extract_entity_relations.py
> +    with open(args.filtered_entities) as reader:
I don't quite follow. Does adding an argument count as business logic? This argument seems pretty business agnostic

2021-07-13 15:34 UTC, anthonywchen commented on retrieval_augmented_linking/generate_data/extract_entity_relations.py
> +                    line = json.loads(line.strip()[:-1])
Ah no. This is a bit of a hack I should fix. The first and last lines of the file are "{" and "}" respectively so I should just use an if/else block here.

2021-07-13 15:37 UTC, samanz-verneek commented on retrieval_augmented_linking/generate_data/extract_entity_relations.py
> +    with open(args.filtered_entities) as reader:
Sorry, I think this wasn't clear. This reading code fit's better in a method that main calls. For instance, if later we want to be able to call that from a library we can easily do that. With the current setup, if we want to read as a library, we'd have to call `main`.

2021-07-13 15:38 UTC, samanz-verneek commented on retrieval_augmented_linking/generate_data/extract_entity_relations.py
> +                    line = json.loads(line.strip()[:-1])
That's fine. Python style seems to like these try, except blocks over if/else in ways that I've never been too comfortable with coming from other langs. I think a comment instead about why you use it is fine.

2021-07-13 15:42 UTC, anthonywchen commented on retrieval_augmented_linking/generate_data/generate_gold_links.py
> +def generate_link_dict(entity_information, head_entity, relation, tail_entity):
Yup good point.

2021-07-13 15:44 UTC, anthonywchen commented on retrieval_augmented_linking/generate_data/filter_entities.py
> +def dumb_filter(line):
it is, I should abstract and make it's own utils.py file

2021-08-05 20:29 UTC, samanz-verneek requested changes

2021-08-05 20:29 UTC, samanz-verneek commented on retrieval_augmented_linking/real/dataset.py
> +        quantizer = faiss.IndexHNSWFlat(embed_dim, hnsw_m)
Can you comment on what these are and why used?

2021-08-05 20:29 UTC, samanz-verneek commented on train_real.py
> +    Save a checkpoint every N steps, instead of Lightning's default that checkpoints
Seems like this callback does more than this? Also, wondering why all this needs to be a callback? can't some be in the LightningModule?

2021-08-05 20:29 UTC, samanz-verneek commented on train_real.py
> +    def save_checkpoint(self, trainer):
Maybe the checkpoint logic should be it's own callback?

2021-08-06 16:02 UTC, giannisp-verneek requested changes

2021-08-06 16:19 UTC, samanz-verneek commented on evaluate_real.py
> +    assert len(nearest_neighbors_list[0]) == args.num_neighbors
What's wrong with assert here?

2021-08-06 19:20 UTC, giannisp-verneek approved these changes

2021-08-06 19:22 UTC, merged